:experimental:
ifdef::env-github[]
:icons:
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:imagesdir: imgs/

== Precautions
=== For applying vinyl glue
. Wear nitrile gloves while handling, as vinyl glue is toxic to touch before it dries.
- Latex gloves will deteriorate on contact with vinyl glue.
. Heat acts as removal for vinyl glue; don't try gluing while in direct sunlight.

=== For handling vinyl
. Avoid contact with vinyl if there is anything applied to your skin that easily soaks into it, such as sunscreens or lotions.

. Vinyl can be stretched out further than normal for bigger inflation, but will degrade the vinyl and make seams weakened: +
- Long exposure to direct sun-light.
- Using a steam cleaner to push steam into a vinyl-based toy.

* Use 0.3mm (softer) up to 0.4mm/16 Gauge/16 Mil (stiffer) vinyl instead.
** Too stiff of vinyl will transfer stress to its surroundings.

* Avoid using the following:
** Non-vinyl glues, such as Gorilla Glue and other superglue products.
** Duct tape and other forms of tape not meant for Vinyl.
** 1mm vinyl thickness won't stick well to seams.

=== Storing vinyl
. Avoid putting vinyl inside dyed/pigmented fabric bags, it will stain the vinyl.
. Leave the toy's valves open to prevent mold build-up while in storage.
.


== Products

=== Self-healing cutting mat

=== Stainless steel rotary cutter

=== Brayer Roller

=== Vinyl Glue

.United States
|===
|Glue |Expected price

|HH-66 Vinyl Cement | $1 per 1 oz.
|Loctite Vinyl, Fabric & Plastic Adhesive | $3 per 1 oz.
|===

=== Vinyl Glue removal

.United States
|===
|Remover |Expected Price

|HH-66 Thinner | $1 per 1oz.
|===

=== UV Flashlight
TIP: Purpose: To see if the vinyl's surface is clean before applying glue to it.

* High quality review sites:
. https://1lumen.com/

|===
|Flashlight |Expected price

|Weltool M2-BF -> the best, but overpriced | $79 with battery and charger included.
|===




== Cleaning

==== Safe to use cleaning liquids:

* Shampoos without conditioners and minerals, such as the https://smartlabel.unileverusa.com/079400587602-0002-en-US/index.html[Suave Essentials - Ocean Breeze].
* Dish soap with no de-greasers, such as the https://dawn-dish.com/en-us/how-to/what-dawn-is-made-of-ingredients[Dawn Original]/Dawn Simply Clean; the page linked also explains most of the ingredients used for Suave's shampoo.


== Finding leaks
. Fill a 32oz spray bottle half-way with warm water, then put 2 tablespoons of a non-concentrated dish soap (such as Dawn Original; also called "Non-Concentrated Simply Clean") into the bottle, then fill the bottle to completion with warm water.
. Spray the entire toy, wait a few hours, then look for expanded bubbles. Some leaks are noticeable after a few minutes.
** Avoid leaving the soap on for beyond half a day, it can leech plasticizers, thus damaging the toy and negatively changing how it feels.

NOTE: To clean off the toy, use a microfiber cloth soaked in warm water.


== Trimming vinyl to make strips
* Use a Paper Guillotine to make precise cuts.


== Applying vinyl glue
* Keep the application flat/even, and cover the entire surface area of what you're gluing on.
** Too much glue applied in an area won't hold together, and might leech plasticizers.

== Going beyond tips and tricks
Whale Man's https://www.youtube.com/@candycoatedkink[various tutorial videos].
