

== Precautions
* For applying glue:
** Don't leave the toy out in the sun.

* Avoid playing with toys if:
** There's sunscreen on yourself.

* Avoid using the following:
** Non-vinyl glues, such as Gorilla Glue and other "super glue" products.
** Duct tape and other forms of tape not meant for Vinyl.
** 1mm vinyl thickness won't stick well to seams. 
*** Use 0.3 (softer) to 0.4mm (stiffer) "16 gauge/16 mil" vinyl instead.
*** Too stiff of vinyl will transfer stress to its surroundings.

== Products

=== Vinyl Glue
.United States
|===
|Glue |Expected price

|HH-66 Vinyl Cement | $1 per 1 oz.
|Loctite Vinyl, Fabric & Plastic Adhesive | $3 per 1 oz.
|===

=== UV Flashlight
TIP: Purpose: To see if the vinyl's surface is clean before applying glue to it.

|===
|Flashlight |Expected price

|Weltool M2-BF (the absolute best) | $79 with battery and charger included.
|===

* High quality review sites:
** https://1lumen.com/

== Cleaning


== Finding leaks
. Fill a 32oz spray bottle half-way with warm water, then put 2 tablespoons of a non-conentrated dish soap (such as Dawn Original; also called "Non-Concentrated Simply Clean") into the bottle, then fill the bottle to completion with warm water.
. Spray the entire toy, wait a few hours, then look for expanded bubbles. Some leaks are noticeable after a few minutes.
** Avoid leaving the soap on for beyond half a day, it can leech plasticizer, thus damaging the toy and negatively changing how it feels.

NOTE: To clean off the toy, use a microfiber cloth soaked in warm water.

== Trimming vinyl to make strips
* Use a Paper Cutter/Guillotine to make precise cuts.

== Applying vinyl glue
* Keep the application flat/even, and cover the entire surface area of what you're gluing on.
** Too much glue applied in an area won't hold together, and might leech plasticizer.